{% set name = "MoorPy" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MoorPy-{{ version }}.tar.gz
  sha256: 959c4cbcf0c7cf1d0ec9acc44efecc888c221fd6e40c0a589aa7292847ad4743
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - matplotlib-base
    - numpy
    - python >=3.9
    - pyyaml
    - scipy

test:
  commands:
    - pip check
  requires:
    - pip
  imports:
    - moorpy

about:
  home: https://github.com/nrel/moorpy
  summary: "A design-oriented mooring system library for Python"
  description: |
      MoorPy is a design-oriented mooring system library for Python based around a
      quasi-static modeling approach.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/nrel/moorpy

extra:
  recipe-maintainers:
    - gbarter
    - mattEhall
